export const STUDENTLOAD = "STUDENTLOAD";
export const STUDENTSUCCESS = "STUDENTSUCCESS";
export const STUDENTERROR = "STUDENTERROR";
export const STUDENTDELETE = "STUDENTDELETE";
export const GETSTUDENTDATA = "GETSTUDENTDATA";